name: readybill
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  avatar_glow: ^3.0.1
  speech_to_text: ^7.0.0
  google_nav_bar: ^5.0.6
  fuzzywuzzy: ^1.2.0
  sqflite: ^2.4.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_tts: ^4.0.2
  provider: ^6.1.2
  flutter_easyloading: ^3.0.5
  permission_handler: ^11.3.1
  internet_connection_checker_plus: ^2.5.2
  fluttertoast: ^8.2.12
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  file_picker: ^8.1.2
  intl: ^0.19.0
  dart_phonetics: ^1.0.1
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.4
  sqlite3: ^2.4.7
  path_provider: ^2.1.5
  just_audio: ^0.9.42
  record: ^5.2.0
  connectivity_plus: 
  pinput: ^5.0.0
  google_maps_flutter: ^2.10.0
  flutter_bluetooth_printer: ^2.17.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  firebase_analytics: ^11.4.1
  flutter_local_notifications: ^18.0.1
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.0.17
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  data_table_2: ^2.5.18


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true


  assets:
  - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
